# Generated by Django 3.2 on 2022-03-06 09:54

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('description', config='english'), name='description_search_vector_idx'),
        ),
    ]
