# Generated by Django 3.2 on 2022-03-06 14:18

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvUploadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=127, unique=True)),
                ('total_rows', models.IntegerField(null=True)),
                ('processed_rows', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('UP', 'Uploaded'), ('PR', 'Processing'), ('FN', 'Finished'), ('FL', 'Failed')], default='UP', max_length=3)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddIndex(
            model_name='csvuploadtask',
            index=django.contrib.postgres.indexes.HashIndex(fields=['task_id'], name='task_id_hash_idx'),
        ),
    ]
